name: CI/CD Pipeline

on:
  push:
    branches:
      - creationapi
      - creationtests
      - main

jobs:
  # ---------------------------------------------------------
  # 1. ÉTAPE : BUILD (Vérification de l'environnement)
  # ---------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Installation et vérification des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

  # ---------------------------------------------------------
  # 2. ÉTAPE : TEST (Validation du code et de la sécurité)
  # ---------------------------------------------------------
  test:
    runs-on: ubuntu-latest
    needs: build # Ne se lance QUE si le build a réussi
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Installation des dépendances pour exécuter les tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Exécution de Pytest
        run: python -m pytest tests/ -v -l -s
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/postgres"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PYTHONPATH: .

  # ---------------------------------------------------------
  # 3. ÉTAPE : DEPLOY (Livraison sur Hugging Face)
  # ---------------------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: test # Ne se lance QUE si les tests sont tous au vert
    if: github.ref == 'refs/heads/main' # Uniquement pour la branche main
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Pousser vers Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ secrets.HF_REPO }} # 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Utilisation dynamique des variables d'environnement
          git remote add hf https://jo:$HF_TOKEN@huggingface.co/spaces/$HF_REPO
          git push --force hf main